version: "3.8"
services:
  database:
    container_name: database-example
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=example
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_USERNAME=admin
      - MONGO_INITDB_PASSWORD=123456
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db

  backend:
    container_name: backend-example
    command: ["npm", "run", "dev"]
    ports:
      - 2000:2000
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGO_SERVER=mongodb://admin:123456@database:27017/example
      - ACCESS_TOKEN_SIGNATURE=mq0AyiLZcG8P8RGrlIVjsKW1q54MDAE0
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - database
    